### PR TITLE
MSPI API and Apollo3p MSPI 

### PR DESCRIPTION
**Pull request by swift-tk**
Things that has been completed.

1. MSPI API and documentation  (mspi.h, mspi.rst)
2. MSPI controller (bus) emulator (mspi_emul.c)
3. MSPI API testcase (tests/drivers/mspi/api)
4. MSPI flash device emulator that implements Zephyr flash API under MSPI bus emulator (flash_mspi_emul_device.c)
5. Apollo3p MSPI controller driver (mspi_ambiq_ap3.c)
6. MSPI flash testcase (tests/drivers/mspi/flash)
7. MSPI APS6404L memc device driver (memc_mspi_aps6404l.c) and added it to the memc sample. (samples/drivers/memc)
8. MSPI ATXP032 flash device driver (flash_mspi_atxp032.c)
9. Add ATXP032 to the MSPI flash testcase
10. MSPI flash sample using ATXP032.(samples/drivers/mspi/mspi_flash)
11. MSPI asynchronous(DMA) sample using APS6404L (samples/drivers/mspi/mspi_async)

### CODE REVIEW

**Review by RichardSWheatley — APPROVED** [review]
Looks good to me.

I think we should start using these pull requests as a way to merge smaller changes to our own HAL prior to trying to merge them to Mainline Zephyr.

As you can see, this will allow us to find issues with code compliance and other issues related to testing.

**Comment by swift-tk** [comment]
@RichardSWheatley I have changed a number of things including variable names and action items in the zephyr pull request.

**Comment by swift-tk** [comment]
There is still bug in UART print, MSPI tests will need to turn off CONFIG_PM_DEVICE_RUNTIME.

**Comment by RichardSWheatley** [comment]
> There is still bug in UART print, MSPI tests will need to turn off CONFIG_PM_DEVICE_RUNTIME.

What bug?

**Pull request merged**
